Fix a missing replacement of FACEBOOK to GLEAN_FACEBOOK.
Summary:
This broke DevRun because Glean server is missing the following flags:

```
ERROR: unknown command line flag 'glean_rocksdb_monitor_thrift_port'
ERROR: unknown command line flag 'rocksdb_resource_metric_report_interval_seconds'
```

Found the cause by bisecting:

```
The first bad revision is:
changeset:   15d58a7136a31cf867fda8425d6e813964c42f9a  D46369066  (@)
user:        Tom Kwong <tomkwong@meta.com>
date:        Mon, 05 Jun 2023 09:13:23 -0700
[Glean] Rename preprocessor constant FACEBOOK to GLEAN_FACEBOOK
```

Reviewed By: donsbot

Differential Revision: D46543181

fbshipit-source-id: e0ec5f47d6bc56dcf92ad05e68ed6ceab882431e