fix maybe type (#200)
Summary:
Pull Request resolved: https://github.com/facebookincubator/Glean/pull/200

D36749593 (https://github.com/facebookincubator/Glean/commit/63cc7f9362c148e4c75477c1b94bbc8aa59f49b2) Broke github CI
```
glean/glass/Glean/Glass/SymbolId/Python.hs:122:46: error:
    • Couldn't match type ‘maybe’ with ‘Maybe’
      Expected type: Angle (Maybe Py.SName_key)
        Actual type: Angle (maybe Py.SName_key)
    • In the second argument of ‘(.=)’, namely ‘maybe_psname’
      In the expression: just (asPredicate psname) .= maybe_psname
      In the first argument of ‘or_’, namely
        ‘[just (asPredicate psname) .= maybe_psname,
          wild .= (predicate Py.SNameToName $ psname .-> pname)]’
    • Relevant bindings include
        maybe_psname :: Angle (maybe Py.SName_key)
          (bound at glean/glass/Glean/Glass/SymbolId/Python.hs:114:6)
    |
122 |           or_ [ just (asPredicate psname) .= maybe_psname,
    |                                              ^^^^^^^^^^^^
cabal: Failed to build lib:glass-lib from glean-0.1.0.0 (which is required by exe:glass-server from glean-0.1.0.0).
```

Differential Revision: D36935501

fbshipit-source-id: 06b8ec0a2139c5f9c42703862ea7e9f981c60466