Fix compilation with gcc
Summary:
```
glean/rts/serialize.h:179:12: error:
     error: explicit specialization in non-namespace scope 'struct facebook::glean::rts::serialize::ThriftCompact'
      179 |   template<> Type typeOf<Nat>() { return NatTy; }
          |            ^
    |
179 |   template<> Type typeOf<Nat>() { return NatTy; }
    |            ^
```

Fortunately it's easy to use a namespace instead of a struct here.

Reviewed By: donsbot

Differential Revision: D46802163

fbshipit-source-id: 5d8c6e9d7eac0408361ef65ff1d57c3fa53bf68a