empty container name for py qname
Summary:
Bug reported by zsol
```
> glass search --language=python main
Error: GlassService::searchByNamePrefix failed with ServerException { message: "QualifiedName: No qualified names found for main" }
> glass describe fbsource/py/third-party/main
Error: Error describing symbol: GlassService::describeSymbol failed with ServerException { message: "QualifiedName: No qualified names found for main" }
```

The problem is that some names are not qualified
```
fbsource.fbcode.python> python.Module { name = "main" }
{ "id": 21872498, "key": { "name": { "id": 21872497, "key": "main" } } }

1 results, 2 facts, 14.65ms, 5369944 bytes, 942 compiled bytes
```

Glass uses a Glean query to compute a pair (container, local_name) which returns no result for such a name.

```
fbsource.fbcode.python> {X0, X1} where python.NameToSName.2 (($21872497 : python.Name.1) -> (python.SName.2 { parent = X2 , local_name = X0 })); X2 = { just = X3 : python.SName }; python.SNameToName.2 (X3 -> X1)

0 results, 0 facts, 6.89ms, 644216 bytes, 1500 compiled bytes
```

The proposed fix is to change this query so as to set container to "" in that case (which is what is done for C++).

I'm wondering why many modules names are unqualified though. This returns many results
```
F where python.DeclarationLocation { file = F, declaration = { module = { name = "main" }}}
```
As a result, we're not able to distinguish between these entities using symbol-ids.

Reviewed By: donsbot

Differential Revision: D36749593

fbshipit-source-id: 6af1b7bad40127a8e27bc8c85e5d4d18b0fc48a3