Fix `-Wreturn-type` warnings
Summary:
Without this diff, the open source build fails with:

```
ast.cpp:497:3: error:
     warning: control reaches end of non-void function [-Wreturn-type]
      497 |   }
          |   ^
```

We fix this by using `folly::assume_unreachable();` to communicate that we don't expect to get to the end.

Reviewed By: phlalx, donsbot

Differential Revision: D55613804

fbshipit-source-id: 2c5f0ee842eba3bbbe6f0316ac0b86c6db27d1bb