Fix stripping of module arguments
Summary:
We were stripping extra arguments after `-fmodule-name=Blah` which
caused problems when the following argument was a 2-part argument,
leading to errors like

```
error: unable to handle compilation, expected exactly one compiler job...
```

This has actually been around for a while, but I only just noticed
when trying to index some fbobjc code after D32664884.

Reviewed By: malanka

Differential Revision: D32800830

fbshipit-source-id: 228b47b5dc9e1b4c5933b7a9a90f429c85c6c6e7