Squelch warming spew that breaks shell test
Summary:
Failures are like this:

```
AssertionError: /data/users/smarlow/eden/fbsource/buck-out/v2/gen/fbsource/98270e95104abfd/third-party/cram/__cram_srcs__/cram_srcs/cram-0.7/cram/_diff.py:19: FutureWarning: Possible nested set at position 19
  return re.match(pattern + b(r'\Z'), s)
!
 --- test-shell.t
+++ test-shell.t.err
@@ -233,8 +233,11 @@

 Recursive expansion is on by default
   $ "$GLEAN" --service "::1:$PORT" shell --db "$DB" ":limit 1" "example.Parent _" | head -n -4
-  [>] :limit 1 (re)
-  [>] example.Parent _ (re)
+  W0224 09:09:37.371766 138264 ThreadLocalStats-inl.h:483] Deleting parent container while 3 stats are registered:
+  W0224 09:09:37.373461 138233 ThreadLocalStats-inl.h:483] Deleting parent container while 2 stats are registered:
+  W0224 09:09:37.373725 138234 ThreadLocalStats-inl.h:483] Deleting parent container while 1 stats are registered:
+  > :limit 1
+  > example.Parent _
   { "id": 1028, "key": { "child": { "id": 1025, "key": { "name": "Lizard", "line": 20 } }, "parent": { "id": 1024, "key": { "name": "Pet", "line": 10 } } } }
```

Reviewed By: pepeiborra, donsbot

Differential Revision: D43565773

fbshipit-source-id: 162b7648f7b3987022c33976fae9f0efb1988cf3