Fix dep in test:backup
```
Preprocessing test suite 'backup' for glean-0.1.0.0..
Building test suite 'backup' for glean-0.1.0.0..
[1 of 1] Compiling BackupTest       ( glean/test/tests/BackupTest.hs, /__w/Glean/Glean/dist-newstyle/build/aarch64-linux/ghc-8.10.7/glean-0.1.0.0/t/backup/build/backup/backup-tmp/BackupTest.o )

glean/test/tests/BackupTest.hs:44:1: error:
    Could not load module ‘Glean.Internal.Types’
    It is a member of the hidden package ‘glean-0.1.0.0’.
    Perhaps you need to add ‘glean’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
44 | import Glean.Internal.Types (Completeness(Complete))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```