Fix CI: add a missing dep for the LocalOrRemote backend (#402)
Summary:
`cabal build glass-regression-go` will work. Fixes

```
Test suite glean-snapshot-go: RUNNING...

glean/glass/test/regression/lib/Glean/Glass/Regression/Tests.hs:28:1: error:
    Could not load module ‘Glean.LocalOrRemote’
    It is a member of the hidden package ‘glean-0.1.0.0’.
    Perhaps you need to add ‘glean’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
28 | import Glean.LocalOrRemote
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Pull Request resolved: https://github.com/facebookincubator/Glean/pull/402

Reviewed By: simonmar

Differential Revision: D51542160

Pulled By: donsbot

fbshipit-source-id: c02dccc58c2d0641a9a29ac56e2576f54e0f1c66