restoreDatabaseFromSite: populate metaBackup (#658)
Summary:
This fixes the following problem:

```
$ glean create --db-root /tmp/g --db test/0 --finish
$ glean backup --db-root /tmp/g test/0 mock:/tmp/b
$ glean delete --db-root /tmp/g --db test/0
$ glean restore --db-root /tmp/g mock:/tmp/b/test.0
I20260107 10:30:07.484591 574661 Env.hs:65] Using schema from dir:/home/simon/.cabal/store/ghc-9.4.7/glean-0.2.0.0-l-db-b1c66a68faaa1c60cea64cb6e1de59f08ce55ddbe40247f16da611febd4a042d/share/glean/schema/source
I20260107 10:30:07.612099 574661 Restore.hs:197] Restoring from mock:/tmp/b/test.0
error: didE20260107 10:30:07.612265 574665 Backup.hs:324] test/0: restore: missing location
 not find database locator mock:/tmp/b/test.0
```

`doRestore` expects to find the locator in `metaBackup`, but when we restore a database using `glean restore`, the entry point is `restoreDatabaseFromSite`, which gets the `Meta` from `Backup.inspect`, which may not populate `metaBackup`. Furthermore it would be hard for `Backup.inspect` to populate this field because it would have to reconstruct the backup locator, which `restoreDatabaseFromSite` already has.

So we just populate `metaBackup` in `restoreDatabaseFromSite`.

Pull Request resolved: https://github.com/facebookincubator/Glean/pull/658

Reviewed By: jjuliamolin

Differential Revision: D90388719

Pulled By: malanka

fbshipit-source-id: 6fac6c5db37bb1fec9797078008ec95750036383