Add request option to enforce specific revision is used
Summary:
We are falling through to the glean lastest revision for every diff nav request (i.e. when a revision is specified but not in the snapshot, we drop down to the glean index). This isn't the desired behavior as it means we build xref responses for every diff.. ouch. The fix is to provide a strict mode that will not consider a db unless the rev matches. Off by default to retain current behavior.

Before:
```
$ buck2 run @//mode/opt //glean/glass/facebook/cli:glass -- --tier glean.glass.dons list-symbols \
  www/html/intern/js/tracery2/configs/webspeed/TrajectoryConfigWebspeed_Utils.js \
  --revision be2f0d8bf00bc13d3c9f49c927061e75f50cb7b9 \
  --show-revision --use-snapshot --limit 2
```

Results in a success: even though we specify revision and use-snapshot:
```
Definitions in www/html/intern/js/tracery2/configs/webspeed/TrajectoryConfigWebspeed_Utils.js at revision e4bc60cfb4e499b9240a9729d34ac17630388e13:
www/html/intern/js/tracery2/configs/webspeed/TrajectoryConfigWebspeed_Utils.js:81:30-81:33 www/js/TrajectoryConfigWebspeed_Utils/row
www/html/intern/js/tracery2/configs/webspeed/TrajectoryConfigWebspeed_Utils.js:267:38-267:43 www/js/TrajectoryConfigWebspeed_Utils/value
```

After: specify --exact-revision and we will get an error immediately instead:

```
[dons@209084.od ~/fbcode/glean (691fff44e)]$ buck2 run @//mode/opt //glean/glass/facebook/cli:glass -- --tier glean.glass.dons list-symbols www/html/intern/js/tracery2/configs/webspeed/TrajectoryConfigWebspeed_Utils.js --revision be2f0d8bf00bc13d3c9f49c927061e75f50cb7b9 --show-revision --limit 2 --exact-revision
```

Produces:

```
Error: Error in www/html/intern/js/tracery2/configs/webspeed/TrajectoryConfigWebspeed_Utils.js: GlassService::documentSymbolListX failed with variant `g`: GlassException { reasons: [exactRevisionNotAvailable("Requested exactly be2f0d8bf00bc13d3c9f49c927061e75f50cb7b9")], revisions: ["e4bc60cfb4e499b9240a9729d34ac17630388e13"] }
```

Existing valid snapshots are unchanged, as the snapshot lookup already checks the rev by design. E.g.
```
$ time buck2 run @//mode/opt //glean/glass/facebook/cli:glass -- --tier glean.glass.dons list-symbols www/flib/intern/codex/ui/codex_type.php --revision 767b8f4dc0792b74cfe8eb79cf936dd7dd938ac1 --show-revision --use-snapshot --limit 2 --exact-revision
Buck UI: https://www.internalfb.com/buck2/80fc0b4f-f87a-401a-982f-18f8463b3211
Jobs completed: 4. Time elapsed: 0.2s.
Definitions in www/flib/intern/codex/ui/codex_type.php at revision 767b8f4dc0792b74cfe8eb79cf936dd7dd938ac1:
www/flib/intern/codex/ui/codex_type.php:4:1-211:2 www/php/:intern:codex:type
www/flib/intern/codex/ui/codex_type.php:14:3-14:53 www/php/:intern:codex:type/VALID_IDENT
www/flib/intern/codex/ui/codex_type.php:8:12-8:16 www/php/:intern:codex:type/:prop/:name
www/flib/intern/codex/ui/codex_type.php:10:10-10:23 www/php/:intern:codex:type/:prop/:short
www/flib/intern/codex/ui/codex_type.php:12:10-12:26 www/php/:intern:codex:type/:prop/:expanded
www/flib/intern/codex/ui/codex_type.php:16:3-145:4 www/php/:intern:codex:type/genRender
www/flib/intern/codex/ui/codex_type.php:147:3-210:4 www/php/:intern:codex:type/genRenderThriftType

real	0m0.953s
user	0m0.368s
sys	0m0.128s
```

Reviewed By: simonmar

Differential Revision: D46789109

fbshipit-source-id: 66b42bf29a07cc4efc7a7930fc6542e3c79bf82e