Update test with valid python code
Summary:
While investigating gaps between pyrefly python indexer and current indexer, I noticed that some supposedly missing references in pyrefly where due to invalid python code instead. So, I am updating the tests with valid code

### Incorrect shadowing of global variables
This test in [shadow.py](https://www.internalfb.com/code/fbsource/fbcode/glean/lang/python/indexers/tests/regression/without_dynamic_import/core/xrefs/shadow.py) was added because the indexer didn't detect a the use of a global variable that was being shadowed in a class (D32053774). A minimal example of this case is:
```
x = 1
class ShadowClass:
   x = x
```
That should work fine, and the use of `x` in the assignment should indeed reference to the global variable previously defined.

However, this is not true for functions. The following program will crash, because, unless it is specify with `nonlocal` or `global`, any reference to `x` within the function will have a local scope.
```
x = 1
def shadow_func():
   x = x

shadow_func()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in shadow_func
UnboundLocalError: cannot access local variable 'x' where it is not associated with a value
```

### Incorrect use of `TypeVar`
From the documentation: https://typing.python.org/en/latest/spec/generics.html

> A TypeVar() expression must always directly be assigned to a variable (it should not be used as part of a larger expression). The argument to TypeVar() must be a string equal to the variable name to which it is assigned. Type variables must not be redefined.

Reviewed By: malanka

Differential Revision: D85243616

fbshipit-source-id: f8d125110b2474e01de3d3c144296cdcb0b19e33